/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeJava */

#ifndef _Included_NativeJava
#define _Included_NativeJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeJava
 * Method:    match_white_dns
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_NativeJava_match_1white_1dns
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
